### ISSUE TITLE
Change the popup alert button style

### ISSUE THREAD

**Issue by Prad-n** [jakobinn/react-popup-alert#2]
Hi 
This is not an issue I think. I need to change the colour associated with success (green) to a different color to go with the overall website style. I dont have a clue how I can submit a style object. Pardon me as I am also new to React so going through a huge learning curve so appreciate your help.
Thanks
Prad

**Comment by jakobinn** [comment]
Hey Prad-n. No worries and thanks for reaching out. You can pass in a style as such: 

buttonStyles={{
backgroundColor: '#your green hex color'
}}
